multipass: true
floatPrecision: 2

plugins:
    - name: preset-default
      params:
          overrides:
              removeViewBox: false
              removeXMLProcInst: true
              removeUselessDefs: true
              cleanupAttrs: true
              cleanupIds: true
              removeComments: true
              removeMetadata: true
              removeTitle: true
              removeDesc: true
              convertColors: true
              convertPathData: true
              mergePaths: true
              removeEmptyContainers: true
              removeEmptyText: true

    - name: inlineStyles
      params:
          onlyMatchedOnce: false
    - name: removeAttrs
      params:
          attrs: "data-name"
    - name: collapseGroups
    - name: removeXMLNS
    - name: convertStyleToAttrs
