name: Code Quality Checks (Force)

on:
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2

            - name: Cache Dependency
              uses: actions/cache/save@v3
              id: cache_dependency
              env:
                  cache-name: cache-dependency
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-node_modules-v1

            - name: Install Dependencies
              run: bun install --frozen-lockfile

            - name: Cache for Turbo
              uses: rharkor/caching-for-turbo@v2.3.1

            - name: Run Type Check
              run: bun run check-types --force

            - name: Run Lint
              run: bun run lint --force
