name: Code Quality Checks

on:
    workflow_dispatch:

    pull_request:
        branches: [main]

jobs:
    code-check:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Dependency restore
              id: cache-restore
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: js-depend-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

            - name: Install dependencies
              if: steps.cache-restore.outputs.cache-hit != 'true'
              run: npm ci

            - name: Lint code
              run: npm run lint

            - name: Run TypeScript type check
              run: npm run type-check
